#!/usr/bin/perl -w
use strict;

$ENV{PATH} = '/var/qmail/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin';

my $SA = '/var/qmail/alias/self-approved';

use Digest::MD5;

undef $/;
my $email = <>;
my $message = "invalid confirmation email.";

my $secret = "PhPSeCrEt";

my ($hash, $sender) = split /-/, $ENV{EXT3}, 2;

unless ($hash && $sender) {
  print <<MOOCOW;
did not understand this bounce message.
MOOCOW
  exit 100;
}

$sender =~ s/=/\@/g;

if ($hash ne Digest::MD5::md5_hex($secret.$sender)) {
  print <<MOOCOW;
the hash and email address did not match.
MOOCOW
  exit 100;
}

system "ezmlm-sub",
       "$SA/bounced", $sender;
system "ezmlm-unsub",
       "$SA/pending", $sender;
