#!/usr/bin/perl -w
use strict;

$ENV{PATH} = '/var/qmail/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin';

my $SA = '/var/qmail/alias/self-approved';

use Digest::MD5;

undef $/;
my $email = <>;
my $message = "invalid confirmation email.";

my $secret = "PhPSeCrEt";

if ($email =~ m/\[confirm:\s+([0-9a-f]+)\s+(.+?)\s*\]/s) {
  my ($hash,$sender) = ($1,$2);
  $sender =~ s/\s//g;
  $sender =~ s/^[^\w]+//g; # handle stray quoting characters

  if ($hash ne Digest::MD5::md5_hex($secret.$sender)) {
    $message = "confirmation hash does not match sender email.";
  }
  else {
    system "ezmlm-sub",
      $SA, $sender;
    system "ezmlm-unsub",
      "$SA/pending", $sender;
    system "ezmlm-unsub",
      "$SA/bounced", $sender;
    exit;
  }
}

exec "/var/qmail/bin/bouncesaying", $message;
