#!/bin/sh
# $Id$

# Backup the PEAR/PECL services

basedir=/local/backups
dir=pear-$date

cd $basedir
mkdir $dir || exit 1
mkdir $dir/packages || exit 1
mkdir $dir/pearweb-rest || exit 1
mkdir $dir/bug-patches || exit 1

#
# Apache configuration
#
cp /local/httpd/conf/pear.php.net.conf $dir/
cp /local/httpd/conf/go-pear.org.conf $dir/
cp /etc/crontab $dir/

#
# rrdtool stuff
#
cp -r /local/rrdtool $dir/

#
# Database
#
nice -n 15 mysqldump --quick pear > $dir/pear.sql

#
# Packages
#
for file in /var/lib/pear/*.tgz; do
	cp $file $dir/packages/`basename $file`
done

#
# REST files
#
cp -r /var/lib/pearweb/rest $basedir/$dir/pearweb-rest

#
# Patches in the bug tracker
#
cp -r /var/tmp/pear/patch $basedir/$dir/bug-patches/

#
# Compress the whole stuff in a gzipped tar archive
#
tar cf - $dir | gzip -9 > $basedir/$dir.tar.gz

#
# cleanup
#
rm -r $dir
