#!/bin/sh
# $Id$
# Backup ecelerity configuration data

dir=ecelerity-$date
cd /local/backups
mkdir $dir || exit 1

mysqldump -u nobody -Q accounts > $dir/acounts.sql
cp /opt/msys/ecwebui/config/httpd.conf $dir
cp -r /opt/msys/etc /opt/msys/ecelerity/etc $dir

rm -f /local/backups/ecelerity-$date.tar.bz2
tar cf - $dir | bzip2 -9 > /local/backups/ecelerity-$date.tar.bz2
rm -rf $dir

