#!/bin/sh
# $Id$

# Backup the PEAR/PECL services

basedir=/local/backups
dir=pear-$date

cd $basedir
mkdir $dir || exit 1
mkdir $dir/packages || exit 1
mkdir $dir/pearweb-rest || exit 1
mkdir $dir/bug-patches || exit 1

#
# Apache configuration
#
cp /etc/httpd/conf/*.conf $dir/

#
# Database
#
nice -n 15 mysqldump --quote-names -u pear --password=pear --quick pear > $dir/pear.sql

#
# Packages
#
for file in /home/pear/packages/*.tgz; do
	cp $file $dir/packages/`basename $file`
done

#
# REST files
#
cp -r /home/pear/pearweb/rest $basedir/$dir/pearweb-rest

#
# Patches in the bug tracker
#
cp -r /home/pear/pearweb/patches $basedir/$dir/bug-patches/

#
# Compress the whole stuff in a gzipped tar archive
#
tar cf - $dir | gzip -9 > $basedir/$dir.tar.gz

#
# cleanup
#
rm -r $dir
