#!/bin/sh
# $Id$
# Backup ecelerity configuration data

dir=ecelerity-$date
cd /local/backups
mkdir $dir || exit 1

mysqldump -Q accounts > $dir/acounts.sql
cp /opt/ecapache/conf/httpd.conf $dir
cp -r /opt/ecelerity/etc /opt/ecelerity/custom_modules $dir

rm -f /local/backups/ecelerity-$date.tar.bz2
tar cf - $dir | bzip2 -9 > /local/backups/ecelerity-$date.tar.bz2
rm -rf $dir

