#!/bin/bash

# Update PhD
GIT_FETCH="git fetch --quiet origin"
GIT_RESET="git reset --quiet --hard origin/master"
cd /local/repos/phpdoc/phd
$GIT_FETCH && $GIT_RESET >/tmp/log-phd 2>&1

# Update docs sources
cd /local/repos/phpdoc
svn up >/tmp/log-svn 2>&1

# Build docs
langs=`php -r 'include "/local/mirrors/phpweb/include/languages.inc"; echo implode( " ", array_keys( $ACTIVE_ONLINE_LANGUAGES ) );'`;

for i in $langs; do
# Update the translation files
	/bin/bash /local/systems/build-docs-lang-rsync $i >>/tmp/log-$i 2>&1;
done;

# Build manual lookup db
php /local/systems/gen-phpweb-sqlite-db.php /local/mirrors/phpweb/backend/manual-lookup.sqlite /local/mirrors/phpweb /manual >/dev/null

