#!/bin/sh

PATH=/usr/local/bin:$PATH

if [ $# != 5 ]; then
  echo usage: $0 phpdocdirectory destdirectory langcode workdirectory destdirectory2
  exit 1
fi

PHPDOC=$1
DEST=$2
LANG=$3
DIR=$4
DEST2=$5

echo -n ">>> starting build at: "
date

echo ">>> making work directory ... "
cp -R -u $PHPDOC $DIR
cd $DIR || exit 1

#
# only files that have been translated are utf-8 converted during
# ./configure, therefore the en ./configure needs to be run before any
# of the others are (else cs and de makes will fail, assuming they run
# in alphabetical order).
# NB en doesn't need to be make'd at this point and won't do all the
# work twice, so long as autoconf isn't called twice.  ..
#
echo ">>> running base ./configure (en) "
./configure --with-lang=en || exit 1

echo ">>> running ./configure --with-lang=$LANG ... "
./configure --with-lang=$LANG || exit 1

echo ">>> running make html ... "
make html || exit 1

echo ">>> running make phpweb ... "
make phpweb || exit 1

echo ">>> running make mirror-files ... "
make mirror-files || exit 1

echo ">>> copying html version ... "
rsync -rlpvC --delete --delete-after build/$LANG/html/ $DEST/html/ || exit 1

echo ">>> copying php version ... "
(cd build/$LANG/php; rsync -rlpvC --delete --delete-after --exclude build.log --exclude html . $DEST) || exit 1

echo ">>> copying standalone versions ... "
rsync -rlpvC build/$LANG/*.gz build/$LANG/*.bz2 build/$LANG/*.zip $DEST2 || exit 1

echo -n ">>> finished build at: "
date

echo ">>> success!"
exit 0
