#!/bin/sh

PATH=/usr/local/bin:$PATH

if [ $# != 6 ]; then
  echo usage: $0 phpdocdirectory destdirectory langcode workdirectory destdirectory2 archivepath
  exit 1
fi

PHPDOC=$1
DEST=$2
LANG=$3
DIR=$4
DEST2=$5
HISTORY=$6

echo -n ">>> starting build at: "
date

echo ">>> making work directory ... "
rsync -ru $PHPDOC/ $DIR/
cd $DIR || exit 1

#
# NB: THIS IS NEEDED FOR PHP_GTK_1 BUILD ONLY, BUT WON'T HURT CVS HEAD.
# Only files that have been translated are utf-8 converted during
# ./configure, therefore the en ./configure needs to be run before any
# of the others are (else cs and de makes will fail, assuming they run
# in alphabetical order).
#
echo ">>> running base ./configure (en) "
./configure --with-lang=en || exit 1

echo ">>> running ./configure --with-lang=$LANG --with-history=$HISTORY ... "
./configure --with-lang=$LANG --with-history=$HISTORY || exit 1

echo ">>> running make html ... "
make html || exit 1

echo ">>> running make phpweb ... "
make phpweb || exit 1

echo ">>> running make mirror-files ... "
make mirror-files || exit 1

if test -f scripts/testclasses.xml; then
	echo ">>> running make updates ... "
	make updates || exit 1
fi

if test -f testclasses.xml; then
	echo ">>> running make updates ... "
	make updates || exit 1
fi

echo ">>> copying html version ... "
rsync -rlpvC --delete --delete-after build/$LANG/html/ $DEST/html/ || exit 1

echo ">>> copying php version ... "
(cd build/$LANG/php; rsync -rlpvC --delete --delete-after --exclude build.log --exclude html --exclude 'updates*.php' . $DEST) || exit 1

echo ">>> copying standalone versions ... "
rsync -rlpvC build/$LANG/*.gz build/$LANG/*.bz2 build/$LANG/*.zip $DEST2 || exit 1

if test -f testclasses.xml; then
	rsync -au testbuild/updates.php $DEST/updates-current.php || exit 1
fi

if test -f testbuild/updates-$lang.php; then
	rsync -au testbuild/updates-$lang.php $DEST/updates.php || exit 1
fi

echo -n ">>> finished build at: "
date

echo -n ">>> running make clean ... "
make clean || exit 1

echo ">>> success!"
exit 0
