#! /bin/sh

ME=`hostname`
SMTP_FROM=systems@php.net
SMTP_TO=systems@php.net
SMTP_SUBJECT="php.net systems: failed jobs on $ME"
SMTP_INTRO="please check /var/log/php-cron-box.log on $ME for details"

FAIL_LOGFILE=/var/log/php-cron-box.fail

if ! test -r $FAIL_LOGFILE; then
    exit 0
fi

(echo $SMTP_INTRO; echo; cat $FAIL_LOGFILE) | \
    mail -s "$SMTP_SUBJECT" -r $SMTP_FROM -- $SMTP_TO

rm -f $FAIL_LOGFILE
