#!/bin/sh
# $Id$
# Check out a web from PHP cvs

export CVSROOT=":pserver:cvsread@cvs.php.net:/repository"
export HOME=/local/.home-for-anon-cvs-checkouts

if [ ! -d $HOME ] ; then
	mkdir $HOME
	# "log in" to cvs
	echo "/1 :pserver:cvsread@cvs.php.net:2401/repository A:c:E?" > $HOME/.cvspass
fi

for WEB in $* ; do
	if [ ! -d /local/mirrors/$WEB ] ; then
		cd /local/mirrors && cvs -z6 -d $CVSROOT co $WEB
	else
		cd /local/mirrors && cvs -z6 -d $CVSROOT -Q upd -dP 2>&1 | grep -v 'is not (any longer) pertinent'
	fi

done
