#!/usr/bin/env php
<?php

// Connect and generate the list from the DB
if (@mysql_connect("localhost","nobody","")) {
  if (@mysql_select_db("phpmasterdb")) {
    $res = @mysql_query("SELECT username,name,email FROM users WHERE cvsaccess");
    if ($res) {
      while ($row = @mysql_fetch_array($res)) {
        echo "$row[username]:$row[name]:$row[email]\n";
      }
    }
  }
}
