#!/bin/sh
set -e

# Download JpGraph v4.4.2 and drop it where we need it

TMPFILE=/tmp/download.$$
DESTDIR=/local/Web/sites/doc.php.net/include

wget -O ${TMPFILE} 'https://jpgraph.net/download/download.php?p=57'

mkdir -p ${DESTDIR}/jpgraph
tar zxvf ${TMPFILE} -C ${DESTDIR}/jpgraph --strip-components=1
