#!/bin/sh
# $Id$
# Do whatever we need to do to run the "master" facilities

/local/systems/update-systems
rsync -qavzC --timeout=600 --delete --delete-after --filter='P manage/github-config.php' rsync.php.net::php-master-web /local/mirrors/php-master-web

#php -r '
#$token=rtrim(file_get_contents("/local/this-box/CVSPASSTOKEN"));
#include "/local/mirrors/php-master-web/fetch/cvspasswd.php";
#' > /repository/CVSROOT/passwd

/usr/local/bin/php /local/mirrors/php-master-web/scripts/mirror-test

#/local/systems/process-zone-file

if test "$how" = "weekly" ; then
	php /local/mirrors/php-master-web/scripts/mirror-summary
	php /local/mirrors/php-master-web/scripts/email-note-summaries
	php /local/mirrors/php-master-web/scripts/event-weekly-email
fi
