#!/bin/sh
# $Id$
# Do whatever we need to do to run the "master" facilities

co-web php-master-web

php -r '
$token=rtrim(file_get_contents("/local/this-box/CVSPASSTOKEN"));
include "/local/mirrors/php-master-web/fetch/cvspasswd.php";
' > /repository/CVSROOT/passwd

file=/tmp/.dns.$$

if php /local/systems/maintain-master-dns.php > $file ; then
	if named-checkzone php.net $file ; then
		cp $file /local/mirrors/php-master-web/fetch/php.net.zone
		mv $file /var/named/php.net
		killall -HUP named
	fi
fi

if test -f $file ; then
	rm -f $file
fi

