#!/bin/sh

# flush the old rulesets
ipfw -f flush

# set up rate limiting pipe
ipfw pipe 1 config bw 16Kbits/s
# limit to 1 concurrent connection per remote address
ipfw add 100 allow tcp from not 127.0.0.1 to not 127.0.0.1 119 limit src-addr 1
# feed remote NNTP via the rate limiting pipe
ipfw add 101 pipe 1 tcp from not 127.0.0.1 to not 127.0.0.1 119

# Load ad-hoc denied list
for i in `cat /local/systems/news-denied|sort|uniq`;
	do 
	  if test $i != '76.75.200.58'; then
		ipfw add deny tcp from $i to any
	  fi
done;

