#!/bin/sh

file=/tmp/.dns.$$

if php /local/systems/maintain-master-dns.php > $file ; then
	if /usr/sbin/named-checkzone php.net $file ; then
		cp -f $file /local/mirrors/php-master-web/fetch/php.net.zone
		mv -f $file /var/named/php.net
		killall -HUP named
	fi
fi



