#! /bin/sh
PATH=/usr/local/bin:/usr/bin:/bin
d=`date -u +%Y%m%d%H%M`
t=/local/snapshots

do_update ( ) {
  prefix=$1
  
  source=/local/mirrors/$1
  target=$1-$d

  cp -rp $source $target
  find $target -name CVS -o -name .cvsignore | xargs rm -rf
  rm -f $target/.deps $target/ChangeLog*
  (cd $target && ./buildconf --copy && ./genfiles) >/dev/null 2>&1
  f=$target.tar
  tar cf $f $target
  rm -rf $target
  gzip -c9 < $f > $f.gz
  bzip2 -9 < $f > $f.bz2
  rm -f $f
  mv $f* $t

  (cd $t; ln -sf $f.gz $prefix-latest.tar.gz; ln -sf $f.bz2 $prefix-latest.tar.bz2)
}

cd /dev/shm || exit 1

do_update php5
do_update php4-STABLE
do_update php4

# purge files which are older than 12 hours
find $t -name \*tar\* -mmin +540|xargs rm -rf
