#!/bin/sh

#cvsup -1 -s /local/etc/php.cvsup > /dev/null

#find /local/repository -name '#cvs.lock' | xargs rm -rf

svnsync sync --username svnsync file:///local/repository-svn/rsync-base > /dev/null
