#!/bin/sh
#
# build the phd docs using phd itself. inception.

/usr/bin/phd -d /local/src/phd/docs/phd-guide/phd-guide.xml -o /local/Web/sites/doc.php.net/www/phd/docs/ -f bigxhtml -F index.html --verbose 0
