#! /bin/sh
PATH=/usr/local/bin:/usr/bin:/bin
d=`date -u +%Y%m%d%H%M`
t=/local/php/web/snaps/;

fetch_index ( ) {
  cd /local/repository/systems
  git pull > /dev/null;
}

do_update ( ) {
  prefix=$1
  
  source=/local/repository/$1
  target=$1-$d

  cd $source
  git pull > /dev/null;

  cd /dev/shm || exit 1
  cp -rp $source $target
  find $target -name '.git*' | xargs rm -rf
  rm -f $target/.deps $target/ChangeLog*
  (cd $target && ./buildconf --force --copy && ./genfiles) >/dev/null 2>&1
  rm -f $target/buildmk.stamp
  f=$target.tar
  tar cf $f $target
  rm -rf $target
  gzip -c5 < $f > $f.gz
  bzip2 -5 < $f > $f.bz2
  xz -9 < $f > $f.xz;
  rm -f $f
  mv $f* $t

  (cd $t; ln -sf $f.gz $prefix-latest.tar.gz; ln -sf $f.bz2 $prefix-latest.tar.bz2; ln -sf $f.xz $prefix-latest.tar.xz;)
}

fetch_index
do_update php-trunk
do_update php5.3
do_update php5.4
do_update php5.5

# purge files which are older than 12 hours
find $t -name \*tar\* -mmin +540|xargs rm -rf
