#!/bin/sh

/local/mirrors/php-master-web/scripts/update-backend /local/mirrors/phpweb

if ls /local/mirrors/manual-chms/*.chm > /dev/null 2> /dev/null; then
  for i in /local/mirrors/manual-chms/*.chm; do
    /local/bin/checkchm $i
    if [ $? == 0 ]; then
      cp -p $i /local/mirrors/phpweb/distributions/manual
    fi
  done
fi

# get manual notes
mkdir -p /local/mirrors/manual-notes.new
/local/mirrors/php-master-web/scripts/update-user-notes \
      /local/mirrors/manual-notes.new
if [ $? -eq 0 ]; then
  rm -rf /local/mirrors/manual-notes
  mv /local/mirrors/manual-notes.new /local/mirrors/manual-notes
else
  rm -rf /local/mirrors/manual-notes.new
fi

find /local/mirrors/manual-notes -type f | \
  xargs head -1 -q | cut -d '|' -f 2 | sort \
  > /local/mirrors/manual-notes/sections

date +"%s" > /local/mirrors/manual-notes/last-updated

rsync -a --delete --delete-after \
  /local/mirrors/manual-notes/ /local/mirrors/phpweb/backend/notes/

DATE=`date +"%s"`
echo "<?php \$LAST_UPDATED=$DATE; ?>" \
  > /local/mirrors/phpweb/include/last_updated.inc

rm -rf /local/mirrors/phpweb/manual/howto

#cp -a /local/tmp/dochowto \
#     /local/mirrors/phpweb/manual/howto

#cp /local/tmp/GeoIP.dat \
#    /local/mirrors/phpweb/backend
