#!/bin/sh

# Eventually moving everything to this section
for i in phpweb; do
    cd /local/repos/$i
    git fetch origin && git reset --hard origin/master
    git submodule update
    rsync -qrltDvzC --exclude=".git" /local/repos/$i/ /local/mirrors/$i
done

# Websites needing the 'shared' module
for i in docweb php-wiki php-people-web qaweb php-gcov-web php-master-web php-news-web php-bugs-web php-gtk-web; do
    cd /local/mirrors/$i
    git fetch origin && git reset --hard origin/master;
    (cd shared && git fetch origin && git reset --hard origin/master)
done

# Other stuffs
for i in systems doc-editor php-shared php-rmtools talks talks/presentations php-gtk-doc; do
    cd /local/mirrors/$i
    git fetch origin && git reset --hard origin/master;
done

# special case for peclweb because master is b0rked
cd /local/mirrors/peclweb;
git fetch origin && git reset --hard origin/old_auth;

# Systems scripts were dropped down a level at some point.
cd /local/systems;
git fetch origin && git reset --hard origin/master;
