#!/bin/sh

rsync -aC --delete --delete-after --include "core" \
            rsync.php.net::php-analytics-web /var/www/analytics

# replace salt in /var/www/analytics/www/config/config.ini.php
SALT=`cat /local/this-box/matomo.env.salt`
cat /var/www/analytics/www/config/config.ini.php | sed "s/PLACEHOLDERFORSALT-REPLACEDONDEPLOY/${SALT}/" > /tmp/config.ini.php && mv /tmp/config.ini.php /var/www/analytics/www/config/config.ini.php

chown -R www-data:www-data /var/www/analytics
