#!/bin/sh
#
# build the phd docs using phd itself. inception.

/usr/bin/phd --docbook '/local/src/phd/docs/phd-guide/phd-guide.xml' --css 'http://php.net/styles/site.css' --output '/local/Web/sites/doc.php.net/www/phd/docs/' --format 'bigxhtml' --outputfilename 'index.html' --verbose 0
