#!/bin/sh

for i in php-bugs-web systems; do
    cd /local/mirrors/$i
    git reset --hard HEAD && git pull origin master;
done

for i in phpweb php-master-web qaweb php-gtk-web php-gtk-doc php-people-web php-news-web embed-web peclweb talks talks/presentations php-wiki php-rmtools; do
	cd /local/mirrors/$i
	svn up -q
done

exit;

for i in `ls -1 /local/mirrors|grep -v manual`; do
#  echo updating $i mirror
  cd /local/mirrors/$i && cvs -Q upd -dP 2>&1 | \
    grep -v 'is not (any longer) pertinent'
done

#cd /local/mirrors/phpdoc && /usr/bin/autoconf
cd /local/mirrors/php-gtk-doc && /usr/bin/autoconf
#cd /local/mirrors/peardoc && /usr/bin/autoconf
