#!/bin/sh
set -e

cd /local/Web/sites/doc.php.net/scripts

export PHPDOC_GIT_DIR=/local/src/phpdoc
export SQLITE_DIR=/local/Web/sites/doc.php.net/sqlite

mkdir -p ${SQLITE_DIR}

echo "Generating PHP database"
php -q rev.php
echo "... done."
