#!/bin/sh

# lynx is dumb.
TERM=vt100
export TERM

# this rebuilds all of the manuals on sunday, or just the ones
# that have changed in the last day on other days

TMPDIR=/local/tmp
BASE=/local/mirrors/php-gtk-doc
CURDAY=`date +%a%b%d`
dow=`date +"%w"`
len=`echo $BASE/manual | wc -c`
len=`expr $len + 1`
ENBDATE=` cat /local/mirrors/php-gtk-web/manual/en/build.log|grep starting|cut -d ' ' -f 5-|awk '{print $1 $2 $3}'`

if [ -z "$1" -o "$1" == "-f" ]; then
  if [ "$dow" -ne 0 -a "$1" != "-f" ]; then
    pred="-mtime 1"
  else
    pred="-maxdepth 1 -type d"
  fi

#  for a in `find $BASE $pred | cut -c 27- | sed -e 's:/.*$::' | sort | uniq`; do
   for a in `find $BASE/manual $pred | cut -c $len- | sort | uniq`; do
    if [ -f $BASE/manual/$a/language-defs.ent ]; then
        do="$do $a"
     fi
  done
else
  do="$@"
fi

if test -z "$do"; then
  exit
fi

if [ -f $BASE/gen_name_to_id.xsl ]; then
  version=1
fi

echo $do | mail -s "rebuilding php-gtk-doc$version: $do" sfox@php.net andrei@gravitonic.com

if test -z "$version"; then
  # we can drop this after the first successful run - it sets up a permanent archive
  mkdir -p $TMPDIR/history-build-gtk/manual
  cp /local/mirrors/php-gtk-web/manual/en/updates.php $TMPDIR/history-build-gtk/updates-en.php
  # this is to get around the limitations imposed by the 'clean' structure
  mkdir -p $TMPDIR/gtk-meta
  cp /local/mirrors/php-gtk-web/manual/en/updates.php $TMPDIR/gtk-meta/updates-meta.php
fi

for a in $do; do
  mkdir -p /local/mirrors/php-gtk-web/manual$version/$a
  /local/bin/build-php-gtk-manual /local/mirrors/php-gtk-doc \
    /local/mirrors/php-gtk-web/manual$version/$a $a $TMPDIR/build-gtk-$a \
    /local/mirrors/php-gtk-web/distributions/manual$version \
    $TMPDIR/history-build-gtk > $TMPDIR/build-gtk-$a.log 2>&1
  mv $TMPDIR/build-gtk-$a.log /local/mirrors/php-gtk-web/manual$version/$a/build.log
  if test -f $TMPDIR/build-gtk-$a/testbuild/updates-$a.php; then
    mv $TMPDIR/build-gtk-$a/testbuild/updates-$a.php $TMPDIR/history-build-gtk/updates-$a.php
    php $TMPDIR/build-gtk-$a/scripts/merge_updates.php $TMPDIR/history-build-gtk-$a/updates-$a.php $TMPDIR/gtk-meta/updates-meta.php
  fi
  if test -z "$version"; then
    mv $TMPDIR/build-gtk-$a/manual/$a $TMPDIR/history-build-gtk/manual
  fi
  rm -rf $TMPDIR/build-gtk-$a
done

if test -z "$version"; then
  rsync -au $TMPDIR/gtk-meta/updates-meta.php /local/mirrors/php-gtk-web/manual/updates.php
  rm -rf gtk-meta
fi
