#!/bin/sh

rsync -aC --delete --delete-after --exclude=logs --exclude=uploads --exclude=local_config.php \
	    rsync.php.net::php-bugs-web /srv/bugs.php.net
chown -R www-data.www-data /srv/bugs.php.net

# update the mysql config file
rsync -az /local/systems/bugs.php.net/additional.mysql.cnf /etc/mysql/conf.d/additional.mysql.cnf
