#!/bin/sh
set -e

mkdir -p /local/src/phpdoc
cd /local/src/phpdoc

# We rely on include/languages.inc from the web-php repo to know what
# languages we want to keep track of
rsync rsync.php.net::phpweb/include/languages.inc .

langs=`/usr/bin/php -r 'include "languages.inc"; echo implode( " ", array_keys( $LANGUAGES ) );'`;
langs="base $langs"

for i in phd; do
    if [ -d /local/src/phpdoc/$i ]; then
        cd /local/src/phpdoc/$i
        echo -n "updating $i: "
        git fetch origin && git reset --hard origin/master
    else
        cd /local/src/phpdoc
        echo -n "cloning $i: "
        git clone https://github.com/php/phd.git phd
    fi
done

for lang in $langs; do
    cd /local/src/phpdoc
    lang=$(echo ${lang} | tr '[:upper:]' '[:lower:]')
    if [ -d ${lang} ]; then
        cd ${lang}
        echo -n "updating ${lang}: "
        git fetch origin && git reset --hard origin/master
    else
        echo -n "cloning ${lang}: "
        git clone https://github.com/php/doc-${lang}.git ${lang}
    fi
done
