#! /bin/sh

cd /local/log || exit 1

mkdir -p old
rev=
for i in access_log.*; do
  rev="$i $rev"
done

for i in $rev; do
  n=old/access_log.`date +%s`
  mv $i $n || exit 1
  cat $n | setuidgid sas /local/modlogan/bin/modlogan
done
