#! /bin/sh

cd /local/log/old || exit 1

rev=`ls -tr access*|tail -10`

echo $rev
for i in $rev; do
  cat $i | /local/modlogan/bin/modlogan
done


#cat $rev | setuidgid sas /local/modlogan/bin/modlogan

