#! /bin/sh

l=/local/log/thttpd.log
pidfile=/var/run/thttpd.pid
webdir=/local/Web/stats/downloads
webconf=php.conf
ending=php

#exit 1

# kill -HUP does not seem to work

#mv $l $l.old
#kill -HUP `cat $pidfile`

cd $webdir && /usr/local/bin/webalizer -c $webconf -x $ending < $l.old
#rm $l.old

