#! /bin/sh

. common

daemontools=daemontools-0.70
dnscache=dnscache-1.00

wget http://cr.yp.to/daemontools/$daemontools.tar.gz
wget http://cr.yp.to/dnscache/$dnscache.tar.gz

tar xfz $daemontools.tar.gz
cd $daemontools
echo "gcc $CFLAGS">conf-cc
make -j2
make setup
cd ..

tar xfz $dnscache.tar.gz
cd $dnscache
echo "gcc $CFLAGS">conf-cc
make -j2
make setup
cd ..

dnscache-conf dnscache dnslog /etc/dnscache

