#! /bin/sh
#
# Created by configure

"./configure" \
"--host=i686-pc-linux-gnu" \
"--with-mysql=/usr/local/mysql" \
"--with-config-file-path=/local/cgi" \
"--with-imap=/usr/local" \
"--with-gd=/home/rasmus/gd-2.0.1" \
"--with-zlib-dir=/usr" \
"--with-freetype-dir=/usr" \
"--enable-gd-native-ttf" \
"--enable-gd-imgstrttf" \
"--with-jpeg-dir=/usr" \
"--with-png-dir=/usr" \
"--with-pdflib=/usr/local" \
"--enable-exif" \
"--disable-debug" \
"--enable-inline-optimization" \
"--with-swf=/usr/local" \
"--with-expat=/usr/local" \
"--with-sablot=/usr/local" \
"" \
"$@"
