#! /bin/sh
#
# Created by configure

'./configure' \
'--host=i686-pc-linux-gnu' \
'--with-mysql=/local/mysql' \
'--enable-exif' \
'--disable-debug' \
'--enable-inline-optimization' \
'--with-snmp=/usr' \
'--with-apxs=/local/httpd/bin/apxs' \
'--with-gd=/home/jimw/gd-2.0.1' \
'--with-openssl' \
'--with-config-file-path=/local/httpd/conf' \
'--with-png-dir=/usr' \
'--with-jpeg-dir=/usr' \
'--enable-gd-native-ttf' \
'--enable-gd-imgstrttf' \
'--with-freetype-dir=/usr' \
'--with-expat' \
'--with-zlib-dir=/usr' \
"$@"
