#!/bin/sh

FILE=/repository/CVSROOT/passwd

wget -q -O $FILE~ http://master.php.net/fetch/cvspasswd.php?token=$TOKEN

if test $? -eq 0 -a -s $FILE~; then
  mv $FILE~ $FILE
else
  echo failed to update $FILE
  rm -f $FILE~
  exit 1
fi

exit 0
