#! /bin/sh

rsync -aC --delete --delete-after --exclude=logs \
   rsync.php.net::php-bugs-web /local/Web/sites/php-bugs-web

rsync -aC --delete --delete-after --exclude=logs \
   rsync.php.net::php-master-web /local/Web/sites/php-master-web

rsync -aC --delete --delete-after --exclude=logs \
   rsync.php.net::qaweb /local/Web/sites/qaweb

rsync -aC --delete --delete-after --exclude=logs \
   rsync.php.net::smarty-web /local/Web/sites/smarty-web

rsync -aC --delete --delete-after --exclude=logs \
   rsync.php.net::php-hosts-web /local/Web/sites/php-hosts-web

rsync -aC --delete --delete-after --exclude=logs \
   rsync.php.net::php-gtk-web /local/Web/sites/php-gtk-web
