#!/bin/sh

logdir=/local/log
webdir=/local/Web/stats/phpweb

webconf=php.conf
ending=php

cd $logdir

# force squid to rotate the logs, and process them
/local/squid/bin/squid -k rotate
sleep 3
cat access_log.* | \
  (cd $webdir && webalizer -Q -c $webconf -x $ending)

# delete all but the most recent error log
current=`echo error_log*`
set $current
eval lastone=\$$#
for j in $current; do
  if test $j != $lastone; then
    delete_files="$delete_files $j"
  fi
done
rm -f $delete_files
