#!/bin/sh

# Updates (pear|pecl).php.net from rsync
#
# public_html/rest must be excluded because these are symlinks on the
# destination machine pointing to the static XML files for the installer.
#
# 4       *       *       *       *       root    /usr/local/www/update 2&1>/dev/null
#
# $Id$

/usr/local/bin/rsync -aC --delete --delete-after --exclude=logs --exclude=public_html/rest \
    rsync.php.net::pearweb /usr/local/www/pearweb
/usr/local/bin/rsync -aC --delete --delete-after --exclude=logs --exclude=public_html/rest \
    rsync.php.net::peclweb /usr/local/www/peclweb
