#!/bin/sh

# Updates MySQL
#
# $Id$

if [ -z "$1" ]
then
    echo "No MySQL version provided"
    exit
fi

base=/usr/local/
url="http://mysql.mirrors.pair.com/Downloads/MySQL-4.0/mysql-standard-$1-unknown-freebsd4.7-i386-linuxthreads.tar.gz"
dir="mysql-standard-$1-unknown-freebsd4.7-i386-linuxthreads"
file="${dir}.tar.gz"

cd $base
wget -nc $url
tar -xzf $file
rm -r $dir/data
ln -s /var/lib/mysql $dir/data
/usr/local/etc/rc.d/mysql-server.sh stop
rm mysql
ln -s $dir mysql
/usr/local/etc/rc.d/mysql-server.sh start
