#!/usr/bin/env php
<?php
$org = 'php';

$token = getenv("GITHUB_TOKEN")
    or die("Must set GITHUB_TOKEN in the environment to allow connection");

$ctx = stream_context_create([
    'http' => [
        'header' => [
            'User-agent: dump-gh-org/0.0',
            'Accept: application/vnd.github+json',
            'Authorization: Bearer ' . $token,
            'X-GitHub-Api-Version: 2022-11-28'
        ],
    ]
]);

echo "===== Organization Members =====\n\n";

function print_members(string $url, $ctx) {
    $page = 1;
    while ($members = json_decode(file_get_contents($url . '?page=' . $page++, false, $ctx))) {
        foreach ($members as $member) {
            echo " * [[{$member->html_url}|{$member->login}]]\n";
        }
    }
}
print_members("https://api.github.com/orgs/{$org}/members", $ctx);

echo "\n";

echo "===== Teams and Members =====\n\n";

$teams = json_decode(file_get_contents("https://api.github.com/orgs/{$org}/teams", false, $ctx));

foreach ($teams as $team) {
    echo "==== [[{$team->html_url}|{$team->name}]]: {$team->description} ====\n\n";

    print_members("https://api.github.com/orgs/{$org}/teams/{$team->slug}/members", $ctx);

    echo "\n";
}
